/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_ntnu_stud_torbjovn_comedielevator_NativeInterface */

#ifndef _Included_no_ntnu_stud_torbjovn_comedielevator_NativeInterface
#define _Included_no_ntnu_stud_torbjovn_comedielevator_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef no_ntnu_stud_torbjovn_comedielevator_NativeInterface_DIRN_DOWN
#define no_ntnu_stud_torbjovn_comedielevator_NativeInterface_DIRN_DOWN -1L
#undef no_ntnu_stud_torbjovn_comedielevator_NativeInterface_DIRN_STOP
#define no_ntnu_stud_torbjovn_comedielevator_NativeInterface_DIRN_STOP 0L
#undef no_ntnu_stud_torbjovn_comedielevator_NativeInterface_DIRN_UP
#define no_ntnu_stud_torbjovn_comedielevator_NativeInterface_DIRN_UP 1L
#undef no_ntnu_stud_torbjovn_comedielevator_NativeInterface_BUTTON_CALL_UP
#define no_ntnu_stud_torbjovn_comedielevator_NativeInterface_BUTTON_CALL_UP 0L
#undef no_ntnu_stud_torbjovn_comedielevator_NativeInterface_BUTTON_CALL_DOWN
#define no_ntnu_stud_torbjovn_comedielevator_NativeInterface_BUTTON_CALL_DOWN 1L
#undef no_ntnu_stud_torbjovn_comedielevator_NativeInterface_BUTTON_COMMAND
#define no_ntnu_stud_torbjovn_comedielevator_NativeInterface_BUTTON_COMMAND 2L
/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_init
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1init
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_set_motor_direction
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1set_1motor_1direction
  (JNIEnv *, jobject, jint);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_set_button_lamp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1set_1button_1lamp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_set_floor_indicator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1set_1floor_1indicator
  (JNIEnv *, jobject, jint);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_set_door_open_lamp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1set_1door_1open_1lamp
  (JNIEnv *, jobject, jint);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_set_stop_lamp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1set_1stop_1lamp
  (JNIEnv *, jobject, jint);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_get_button_signal
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1get_1button_1signal
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_get_floor_sensor_signal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1get_1floor_1sensor_1signal
  (JNIEnv *, jobject);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_get_stop_signal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1get_1stop_1signal
  (JNIEnv *, jobject);

/*
 * Class:     no_ntnu_stud_torbjovn_comedielevator_NativeInterface
 * Method:    elev_get_obstruction_signal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_no_ntnu_stud_torbjovn_comedielevator_NativeInterface_elev_1get_1obstruction_1signal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
